<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
	<TargetFramework>net10.0</TargetFramework>
	<IsTestProject>true</IsTestProject>
	<IsPackable>false</IsPackable>
	<LangVersion>latest</LangVersion>
	<DisableTransitiveProjectReferences>false</DisableTransitiveProjectReferences>
	<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
	<PackageReference Include="MSTest" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\..\src\CondoScope.Domain\CondoScope.Domain.csproj" />
	<ProjectReference Include="..\..\src\CondoScope.Persistence\CondoScope.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
	<Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

</Project>
